config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  get 'contact', to: 'toppages#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]
    if login(email, password)
      flash[:primary] = "ログインしました"
      redirect_to @user
    else
      flash[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:primary] = "ログアウトしました"
    redirect_to root_url
  end

  private

    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        session[:user_id] = @user.id
        return true
      else
        return false
      end
    end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: %i(index show)

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:primary] = '新規登録しました'
      redirect_to @user
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_dialog.html.erb
<div id="modal-center" class="uk-flex-top" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">

        <button class="uk-modal-close-default" type="button" uk-close></button>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
      <h1><a class="uk-link-reset" href="/">suzuki's web_site</a></h1>
    </div>
        <div class="uk-navbar-right"> 
        <% if logged_in? %> 
            <ul class="uk-navbar-nav">
                <li>
                    <a href="#">Menu</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li class="#"><a href="/">TOP</a></li>
                            <li><%= link_to 'logout', logout_path, method: :delete %></li>
                            <li>
                        </ul>
                    </div>
                </li>
            </ul>
            <button class="uk-button uk-button-secondary uk-margin-small-right" type="button" uk-toggle="target: #modal-close-outside">profile</button>
            <div id="modal-close-outside" uk-modal>
                <div class="uk-modal-dialog uk-modal-body">
                    <button class="uk-modal-close-outside" type="button" uk-close></button>
                    <div class="uk-width-auto">
                            <img class="uk-border-circle" width="80" height="80" src=".jpg">
                    </div>
                    <h2 class="uk-modal-title">自己紹介</h2>
                    <p>岩手県釜石市生まれ。高校卒業後、宮城県仙台市で医療機関・コールセンターを経て震災を機にUターン。
                        地元で働くも、WEBエンジニアを志すべく転職活動中。最終目標は<strong>「納品のない受託開発」</strong>。<br>制作物はこちら=><a href="#"> github <i uk-icon="icon: github-alt"></i></a></p>
                </div>
            </div>
            <div class="uk-margin">
                <form class="uk-search uk-search-default">
                <a href="/" class="uk-search-icon-flip" uk-search-icon></a>
                    <input class="uk-search-input" type="search" placeholder="Search...">
                </form>
            </div>
        <% else %>
            <ul class="uk-navbar-nav">
                <li>
                    <a href="#">Menu</a>
                    <div class="uk-navbar-dropdown">
                        <ul class="uk-nav uk-navbar-dropdown-nav">
                            <li><%= link_to 'log in', login_path %></li>
                            <li><%= link_to 'create account', signup_path %></li>
                        </ul>
                    </div>
                </li>
            </ul>
         <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title><%= yield(:title) %> | suzuki's web_site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/contact.html.erb
<form class="uk-form-horizontal uk-margin-large">
  <div class="uk-margin">
    <label class="uk-form-label" for="form-horizontal-text">Text</label>
    <div class="uk-form-controls">
      <input
        class="uk-input"
        id="form-horizontal-text"
        type="text"
        placeholder="Some text..."
      />
    </div>
  </div>

  <div class="uk-margin">
    <label class="uk-form-label" for="form-horizontal-select">Select</label>
    <div class="uk-form-controls">
      <select class="uk-select" id="form-horizontal-select">
        <option>Option 01</option>
        <option>Option 02</option>
      </select>
    </div>
  </div>

  <div class="uk-margin">
    <div class="uk-form-label">Radio</div>
    <div class="uk-form-controls uk-form-controls-text">
      <label
        ><input class="uk-radio" type="radio" name="radio1" /> Option 01</label
      ><br />
      <label
        ><input class="uk-radio" type="radio" name="radio1" /> Option 02</label
      >
    </div>
  </div>
</form>

app/views/toppages/index.html.erb
<% provide(:title, "Home") %>
<pre>ようこそ、suzuki's web_siteへ。</pre>
  <% if logged_in? %>
    <p>ログインユーザ: <%= current_user.name %></p>
  <div id="main">
    <p>Find me in app /<a href="#"> github <i uk-icon="icon: github-alt"></i></a></p>
  </div>
  <main uk-grid>
      <div class="uk-card uk-width-1-2@m">
        <div class="uk-card-header">
          <h3>当サイトの主旨 <i uk-icon="icon: check"></i></h3>
        </div>
        <div class="uk-card-body">
          <span>
            情報提供を目的としています。<br>
            これまでの経験で学んだこと・情報を中心に掲載したいと思います。
          </span>
        </div>
        <div class="uk-card-body">
        </div>
      </div>
      <div class="uk-card uk-width-1-2@m">
        <div class="uk-card-header">
          <h3>プログラミングについて <i uk-icon="icon: code"></i></h3>
        </div>
        <div class="uk-card-body">
          <span>
            今後（既に…）IT業界では人材不足が顕著とのこと。
            プログラミングスクールも大人気のようですね。
            また、コロナウイルスに端を発する景気の落ち込みが実際のものとなっていることもあり
            テレワークの拡大・充足が急がれています。
            手に職という意味でも必要なスキルになってきています。
          </span>
        </div>
      </div>
      <button class="uk-button uk-button-text uk-width-1-1" type="button" uk-toggle="target: #offcanvas-nav"><a href="#">記事一覧・お問い合わせ</a></button>

      <div id="offcanvas-nav" uk-offcanvas="overlay: true">
        <div class="uk-offcanvas-bar">
          <button class="uk-offcanvas-close" type="button" uk-close></button>
            <ul class="uk-nav uk-nav-default">
                <li class="uk-nav-header">目次</li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: table"></span> 投稿記事</a></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: twitter"></span> twitter</a></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: facebook"></span> Facebook</a></li>
                <li class="uk-nav-divider"></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span> お問い合わせ</a></li>
            </ul>
        </div>
      </div>
    <div class="uk-child-width-1-3@m" uk-grid uk-scrollspy="cls: uk-animation-slide-bottom; target: .uk-card; delay: 300; repeat: true">
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-body">
                  <h3 class="uk-card-title">テレワーク</h3>
                  <p>地方在住であることは<br>もはやハンディキャップにはなりません。
                    </p>
              </div>
              <div class="uk-card-media-bottom">
                  <%= image_tag '1559821.jpg' %>
              </div>
          </div>
      </div>
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-media-top">
                  <%= image_tag '4078456.jpg'%>
              </div>
              <div class="uk-card-body">
                  <h3 class="uk-card-title">時間の有効活用</h3>
                  <p>時間はみな平等です。<br>あなたの24時間を有効に使うべきです。</p>
              </div>
          </div>
      </div>
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-body">
                  <h3 class="uk-card-title">夢を叶えよう</h3>
                  <p>人生は一度きりです。<br>まずは行動してみましょう。
                    </p>
              </div>
                  <div class="uk-card-media-bottom">
                      <%= image_tag '1831236.jpg' %>
                  </div>
          </div>
      </div>
    </div>
  </main>
  <% else%>
  <% end %>

  

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'トップページへ', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h2>Sign up</h2>
</div>

<div class="uk-grid-small uk-child-width-expand@s uk-text-center" uk-grid>

    <%= form_with(model: @user, local: true) do |f| %>
      
      <div class="form-group">
        <%= f.label :name, '名前' %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Eメール' %><br>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %><br>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %><br>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <br>

      <%= f.submit 'Sign up', class: 'uk-button uk-button-primary' %>
    <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, "Home") %>
<pre>ようこそ、suzuki's web_siteへ。</pre>
  <% if logged_in? %>
    <p>ログインユーザ: <%= current_user.name %></p>
  <div id="main">
    <p>Find me in app /<a href="#"> github <i uk-icon="icon: github-alt"></i></a></p>
  </div>
  <main uk-grid>
      <div class="uk-card uk-width-1-2@m">
        <div class="uk-card-header">
          <h3>当サイトの主旨 <i uk-icon="icon: check"></i></h3>
        </div>
        <div class="uk-card-body">
          <span>
            情報提供を目的としています。<br>
            これまでの経験で学んだこと・情報を中心に掲載したいと思います。
          </span>
        </div>
        <div class="uk-card-body">
        </div>
      </div>
      <div class="uk-card uk-width-1-2@m">
        <div class="uk-card-header">
          <h3>プログラミングについて <i uk-icon="icon: code"></i></h3>
        </div>
        <div class="uk-card-body">
          <span>
            今後（既に…）IT業界では人材不足が顕著とのこと。
            プログラミングスクールも大人気のようですね。
            また、コロナウイルスに端を発する景気の落ち込みが実際のものとなっていることもあり
            テレワークの拡大・充足が急がれています。
            手に職という意味でも必要なスキルになってきています。
          </span>
        </div>
      </div>
      <button class="uk-button uk-button-text uk-width-1-1" type="button" uk-toggle="target: #offcanvas-nav"><a href="#">記事一覧・お問い合わせ</a></button>

      <div id="offcanvas-nav" uk-offcanvas="overlay: true">
        <div class="uk-offcanvas-bar">
          <button class="uk-offcanvas-close" type="button" uk-close></button>
            <ul class="uk-nav uk-nav-default">
                <li class="uk-nav-header">目次</li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: table"></span> 投稿記事</a></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: twitter"></span> twitter</a></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: facebook"></span> Facebook</a></li>
                <li class="uk-nav-divider"></li>
                <li><a href="#"><span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span> お問い合わせ</a></li>
            </ul>
        </div>
      </div>
    <div class="uk-child-width-1-3@m" uk-grid uk-scrollspy="cls: uk-animation-slide-bottom; target: .uk-card; delay: 300; repeat: true">
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-body">
                  <h3 class="uk-card-title">テレワーク</h3>
                  <p>地方在住であることは<br>もはやハンディキャップにはなりません。
                    </p>
              </div>
              <div class="uk-card-media-bottom">
                  <%= image_tag '1559821.jpg' %>
              </div>
          </div>
      </div>
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-media-top">
                  <%= image_tag '4078456.jpg'%>
              </div>
              <div class="uk-card-body">
                  <h3 class="uk-card-title">時間の有効活用</h3>
                  <p>時間はみな平等です。<br>あなたの24時間を有効に使うべきです。</p>
              </div>
          </div>
      </div>
      <div>
          <div class="uk-card uk-card-default">
              <div class="uk-card-body">
                  <h3 class="uk-card-title">夢を叶えよう</h3>
                  <p>人生は一度きりです。<br>まずは行動してみましょう。
                    </p>
              </div>
                  <div class="uk-card-media-bottom">
                      <%= image_tag '1831236.jpg' %>
                  </div>
          </div>
      </div>
    </div>
  </main>
  <% else%>
  <% end %>

  